POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5ld1VzZXIiLCJpZCI6IjYxMjhiNjc2NTE0ZDU0M2RiMDk2NzE2NCIsImlhdCI6MTYzMTEwNjcwNiwiZXhwIjoxNjMxMTEwMzA2fQ.7xgaPk571JL_HrrQSE_8VkAJrWAjnfYS_H19AcUVEmA

{
    "title": "Travel Blog",
    "author": "Traveler",
    "url": "travelblog.com",
    "likes": 15,
    "user": "6124c7f78c07ec3578a0386c"
}